steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/kg-note-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/kg-note-api:latest',
      '.'
    ]
    
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/kg-note-api:$COMMIT_SHA'
    ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/kg-note-api:latest'
    ]
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'kg-note-api',
      '--image=gcr.io/$PROJECT_ID/kg-note-api:$COMMIT_SHA',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=8000',
      '--set-env-vars=PYTHONUNBUFFERED=1',
      '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials:latest',
      '--service-account=kg-note-api@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/kg-note-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/kg-note-api:latest'

# Optional: specify machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8'